/*
 * Copyright (c) 2024. Robin Hillyard
 */

package com.phasmidsoftware.dsaipg.util;

import java.lang.reflect.Array;
import java.util.Collection;
import java.util.Random;
import java.util.function.Function;

/**
 * A utility class providing several static methods for various common operations.
 */
public class Utilities {
    /**
     * There is really no better way that I could find to do this with library/language methods.
     * Don't try to inline this if the generic type extends something like Comparable, or you will get a ClassCastException.
     *
     * @param ts  a collection of Ts.
     * @param <T> the underlying type of ts.
     * @return an array T[].
     */
    public static <T> T[] asArray(Collection<T> ts) {
        if (ts.isEmpty()) throw new RuntimeException("ts may not be empty");
        @SuppressWarnings("unchecked") T[] result = (T[]) Array.newInstance(ts.iterator().next().getClass(), 0);
        return ts.toArray(result);
    }

    /**
     * Create a string representing a double, with three decimal places.
     *
     * @param x the number to show.
     * @return a String representing the number rounded to three decimal places.
     */
    public static String formatDecimal3Places(double x) {
        double scaleFactor = 1000.0;
        return String.format("%.3f", round(x * scaleFactor) / scaleFactor);
    }

    /**
     * Create a string representing an integer, with commas to separate thousands.
     *
     * @param x the integer.
     * @return a String representing the number with commas.
     */
    public static String formatWholeWithCommas(final int x) {
        return String.format("%,d", x);
    }

    /**
     * Create a string representing an integer, with commas to separate thousands.
     *
     * @param x the integer.
     * @return a String representing the number without commas.
     */
    public static String formatWhole(long x) {
        return String.format("%d", x);
    }

    /**
     * Converts a double value to its integer representation as a string without commas.
     *
     * @param x the double value to be converted.
     * @return a string representation of the rounded integer value of the input.
     */
    public static String asInt(double x) {
        final long i = round(x);
        return formatWhole(i);
    }

    /**
     * Rounds the given double value to the nearest long value using {@code Math.round}.
     *
     * @param x the double value to be rounded.
     * @return the closest long to the argument, with ties rounding up.
     */
    public static long round(double x) {
        return Math.round(x);
    }

    /**
     * Fills an array with random values generated using the supplied function and random object.
     *
     * @param <T>    the type of the elements in the array.
     * @param clazz  the class of the type of elements in the array.
     * @param random the Random object used to generate random values.
     * @param n      the number of elements in the array.
     * @param f      a function that takes a Random object and generates a value of type T.
     * @return an array of type T filled with random values generated by the function.
     */
    public static <T> T[] fillRandomArray(Class<T> clazz, Random random, int n, Function<Random, T> f) {
        @SuppressWarnings("unchecked") T[] result = (T[]) Array.newInstance(clazz, n);
        for (int i = 0; i < n; i++) result[i] = f.apply(random);
        return result;
    }

    /**
     * Method to calculate log to tbe base 2 of n.
     *
     * @param n the number whose log we need.
     * @return lg n.
     */
    public static double lg(double n) {
        return Math.log(n) / Math.log(2);
    }

    /**
     * Create a string representing an integer, with commas to separate thousands.
     *
     * @param x the integer.
     * @return a String representing the number with commas.
     */
    public static String formatWhole(final int x) {
        return String.format("%,d", x);
    }
}